# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: MT6000

on:
  # 每天北京时间凌晨 03:00
  schedule:
    - cron: '0 19 * * *'

  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动追加插件包，多个请用\n符号隔开。'
        required: false
        type: string

      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  config:
    name: MT6000

    uses: ./.github/workflows/WRT-CORE.yml

    with:
      WRT_CONFIG: MT6000
      WRT_THEME: argon

      WRT_NAME: GLMT6000_18

      WRT_SSID: MT6000
      WRT_WORD: ljx2026@.

      WRT_IP: 192.168.18.1
      WRT_PW: admin

      WRT_REPO: https://github.com/immortalwrt/immortalwrt.git
      WRT_BRANCH: openwrt-25.12
      WRT_SOURCE: immortalwrt/immortalwrt

      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
